// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1d33888e-a9ee-42e6-a4b6-eecdfc6f429e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rDV5lWC2s",
    "aws_user_pools_web_client_id": "4didltj6fomraut0dvpd4j21c2",
    "aws_content_delivery_bucket": "sumerianamplifyapp-20181215135901-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d26gpbxykf3aqs.cloudfront.net"
};


export default awsmobile;
